# Regenerates the m3-string-requirements.schema.json file based on the current items, flags, techs, and helpers.
# To use: from the sm-json-data directory, run "python3 scripts/update_schema.py"
import json

string_reqs = [
    "free",
    "never",
]
items_json = json.load(open("items.json", "r"))
for item in items_json["implicitItems"]:
    string_reqs.append(item)
for item in items_json["upgradeItems"]:
    string_reqs.append(item["name"])
for item in items_json["expansionItems"]:
    string_reqs.append(item["name"])
for flag in items_json["gameFlags"]:
    string_reqs.append(flag)
    
tech_json = json.load(open("tech.json", "r"))
def walk_techs(tech_list):
    for tech in tech_list:
        string_reqs.append(tech["name"])
        walk_techs(tech.get("extensionTechs", []))
for category in tech_json["techCategories"]:
    walk_techs(category["techs"])

helper_json = json.load(open("helpers.json", "r"))
for category in helper_json["helperCategories"]:
    for helper in category["helpers"]:
        string_reqs.append(helper["name"])
        
string_requirement_schema = {
  "$comment": "DO NOT EDIT THIS FILE MANUALLY. IT IS AUTO-GENERATED BY scripts/update_schema.py",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://raw.githubusercontent.com/vg-json-data/sm-json-data/master/schema/m3-string-requirements.schema.json",
  "type": "string",
  "enum": string_reqs
}
json.dump(string_requirement_schema, open("schema/m3-string-requirements.schema.json", "w"), indent=2)
