# - Regenerates the m3-string-requirements.schema.json file based on items.json, tech.json, helpers.json
# - Regenerates the m3-numeric-parameters.schema.json file based on numerics.json
# To use: from the sm-json-data directory, run "python3 scripts/update_schema.py"
import json
import argparse

argparser = argparse.ArgumentParser(description="Update the m3-string-requirements.schema.json file.")
argparser.add_argument("--verify", action="store_true",
                       help="Verify that the schema is up to date instead of updating it.")
args = argparser.parse_args()

schema_list = []  # list of (path, new_schema)

# m3-string-requirements.schema.json: ---------------------------------------
string_reqs = [
    "free",
    "never",
]
items_json = json.load(open("items.json", "r"))
for item in items_json["implicitItems"]:
    string_reqs.append(item)
for item in items_json["upgradeItems"]:
    string_reqs.append(item["name"])
for item in items_json["expansionItems"]:
    string_reqs.append(item["name"])
for flag in items_json["gameFlags"]:
    string_reqs.append(flag)
    
tech_json = json.load(open("tech.json", "r"))
def walk_techs(tech_list):
    for tech in tech_list:
        string_reqs.append(tech["name"])
        walk_techs(tech.get("extensionTechs", []))
for category in tech_json["techCategories"]:
    walk_techs(category["techs"])

helper_json = json.load(open("helpers.json", "r"))
for category in helper_json["helperCategories"]:
    for helper in category["helpers"]:
        string_reqs.append(helper["name"])
        
string_requirements_obj = {
  "$comment": "DO NOT EDIT THIS FILE MANUALLY. IT IS AUTO-GENERATED BY scripts/update_schema.py",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://raw.githubusercontent.com/vg-json-data/sm-json-data/master/schema/m3-string-requirements.schema.json",
  "type": "string",
  "enum": string_reqs
}
schema_list.append(("schema/m3-string-requirements.schema.json", string_requirements_obj))


# m3-numeric-parameters.schema.json: ---------------------------------------
numeric_json = json.load(open("numerics.json", "r"))
numeric_parameters = []
for category in numeric_json["numericCategories"]:
    for numeric in category["numerics"]:
        numeric_parameters.append(numeric["name"])
numeric_parameters_obj = {
  "$comment": "DO NOT EDIT THIS FILE MANUALLY. IT IS AUTO-GENERATED BY scripts/update_schema.py",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://raw.githubusercontent.com/vg-json-data/sm-json-data/master/schema/m3-numeric-parameters.schema.json",
  "type": "string",
  "enum": numeric_parameters
}
schema_list.append(("schema/m3-numeric-parameters.schema.json", numeric_parameters_obj))        
        
        
# Compare/write updated schemas: ---------------------------------------
for (path, schema_obj) in schema_list:
    old_schema = open(path, "r").read()
    new_schema = json.dumps(schema_obj, indent=2)
    if old_schema == new_schema:
        print(f"Schema {path} is up to date.")
    else:
        if args.verify:
            print(f"🔴 Schema {path} is out of date. Please run 'python3 scripts/update_schema.py' to update it.")
            exit(1)
        else:
            open(path, "w").write(new_schema)
            print(f"Schema {path} updated.")
